spring:
  application:
    name: hamburgueria
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:haburgueria_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
flayway:
  locations: filesystem:db/migration